name: My First Workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: sample bash command
              run: |
                echo "Hello World!"
                ps -axf

            - name: hello
              uses: actions/hello-world-javascript-action@v1

            - name: test action
              id: test-action
              uses: ./.github/actions/action1
              with:
                base-dir: '.'
