name: My First Workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: sample bash command
              run: |
                echo "Hello World!"
                ps -axf

            - name: hello
              uses: actions/hello-world-javascript-action@v1

            - name: test action
              id: test-action-javascript
              uses: ./.github/actions/action-javascript
              with:
                base-dir: '.'
            
            - name: test action
              id: test-action-python
              uses: ./.github/actions/action-python
              with:
                base-dir: '.'
    issues:
        uses: ./.github/workflows/issues.yml