name: My First Workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: sample bash command
              run: |
                echo "Hello World!"
                ps -axf

            - name: hello
              uses: actions/hello-world-javascript-action@v1